gaia:
  dataAdminRoles: []
  prefix: "{{org}}-{{domain}}-{{env}}"
  bedrock:
    enabled: true
    region: ca-central-1
  llms:
    sagemaker: []
  rag:
    engines:
      sagemaker:
        instanceType: ml.inf1.xlarge
      aurora:
        minCapacity: 0.5
        maxCapacity: 4
      knowledgeBase: {}
    embeddingsModels: [
      {
        provider: "bedrock",
        name: "amazon.titan-embed-text-v2:0",
        dimensions: 1024,
        isDefault: true
      }
    ]
    crossEncoderModels: []
  # this block must not be enabled on first deployment of
  # the system.
  #   concurrency:
  #     modelInterfaceConcurrentLambdas: 10
  #     restApiConcurrentLambdas: 5
  #     websocketConcurrentLambdas: 2
  auth:
    authType: email_pass
    cognitoDomain: "{{org}}-{{domain}}-{{env}}"
  setApiGateWayAccountCloudwatchRole: true
  skipApiGatewayDefaultWaf: true
  vpc:
    vpcId: "{{VPC_ID}}"
    appSecurityGroupId: "{{APP_SECURITY_GROUP_ID}}"
    appSubnets:
      - "{{APP_SUBNET_1}}"
      - "{{APP_SUBNET_2}}"
    dataSecurityGroupId: "{{DATA_SECURITY_GROUP_ID}}"
    dataSubnets:
      - "{{DATA_SUBNET_1}}"
      - "{{DATA_SUBNET_2}}"
    createVpcEndpoints: true
    cidrBlock: "10.0.0.0/16"